Algoritmo "Contador1a10"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/09/2023
Var
   // Seção de Declarações das variáveis
   contador, N: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   contador <- 1

   Repita
      EscrevaL(contador)
      contador <- contador + 1
   Ate(contador > 10)
   
   
   
Fimalgoritmo