Algoritmo "contagemRegressivaNumerosPares"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/10/2023
Var
   // Seção de Declarações das variáveis
   C, N: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   EscrevaL("Digite um numero")
   Leia(N)
   se (N % 2 = 0 ) entao
      Para C <- N ate 0 passo -2 faca
         EscrevaL(C)
      FimPara
   fimSe



Fimalgoritmo